x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Initial private listing
    releaseTypes:
      - Feature
    recommended: false
  images:
    cloudnative-pg:
      properties:
        cloudnative-pg.image.repository:
          type: REPO_WITH_REGISTRY
        cloudnative-pg.image.tag:
          type: TAG
    metering:
      properties:
        metering.image.image:
          type: FULL
  clusterConstraints:
    resources:
    - replicas: 1
      requests:
        cpu: 100m
        memory: 256Mi
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_ONE_NODE_PER_REPLICA
    k8sVersion: ">=1.24.0"
  deployerServiceAccount:
    description: >- 
      The deployer service account creates a CustomResourceDefinition for its operator. This custom resource is used to manage the PostgreSQL instances.
      The deployer also creates webhooks to provide validation and defaults for the resources it manages.
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups:
              - 'apiextensions.k8s.io'
            resources:
              - 'customresourcedefinitions'
            verbs:
              - '*'
          - apiGroups:
              - 'admissionregistration.k8s.io'
            resources:
              - 'mutatingwebhookconfigurations'
              - 'validatingwebhookconfigurations'
            verbs:
              - '*'
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: cnpg-system
    x-google-marketplace:
      type: NAMESPACE
  metering.reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  metering.serviceAccountName:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >-
          The metering deployment watches pods and cluster resources in order to measure and bill for the appropriate usage. The pods may reside in arbitrary namespaces, requiring a ClusterRole to be used.
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: view
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups:
                  - ""
                resources:
                  - pods
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - ""
                resources:
                  - nodes
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - ""
                resources:
                  - configmaps
                verbs:
                  - get
                  - update
                  - patch
              - apiGroups:
                  - ""
                resources:
                  - events
                verbs:
                  - create
                  - patch
              - apiGroups:
                  - postgresql.cnpg.io
                resources:
                  - clusters
                verbs:
                  - get
                  - list
                  - watch
  cloudnative-pg.replicas:
    type: integer
    default: 1
  cloudnative-pg.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >-
          The operator is based on a Cluster CustomResource. This operator automatically creates pods and the associated resources to create and manage database instances. These database instances can have arbitrary names and reside in arbitrary namespaces, requiring a ClusterRole for the operator to use.
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups:
              - ""
            resources:
              - configmaps
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - ""
            resources:
              - configmaps/status
            verbs:
              - get
              - patch
              - update
          - apiGroups:
              - ""
            resources:
              - events
            verbs:
              - create
              - patch
          - apiGroups:
              - ""
            resources:
              - namespaces
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - ""
            resources:
              - nodes
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - ""
            resources:
              - persistentvolumeclaims
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - watch
          - apiGroups:
              - ""
            resources:
              - pods
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - watch
          - apiGroups:
              - ""
            resources:
              - pods/exec
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - watch
          - apiGroups:
              - ""
            resources:
              - pods/status
            verbs:
              - get
          - apiGroups:
              - ""
            resources:
              - secrets
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - ""
            resources:
              - secrets/status
            verbs:
              - get
              - patch
              - update
          - apiGroups:
              - ""
            resources:
              - serviceaccounts
            verbs:
              - create
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - ""
            resources:
              - services
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - admissionregistration.k8s.io
            resources:
              - mutatingwebhookconfigurations
            verbs:
              - get
              - list
              - patch
              - update
          - apiGroups:
              - admissionregistration.k8s.io
            resources:
              - validatingwebhookconfigurations
            verbs:
              - get
              - list
              - patch
              - update
          - apiGroups:
              - apiextensions.k8s.io
            resources:
              - customresourcedefinitions
            verbs:
              - get
              - list
              - update
          - apiGroups:
              - apps
            resources:
              - deployments
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - batch
            resources:
              - jobs
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - watch
          - apiGroups:
              - coordination.k8s.io
            resources:
              - leases
            verbs:
              - create
              - get
              - update
          - apiGroups:
              - monitoring.coreos.com
            resources:
              - podmonitors
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - watch
          - apiGroups:
              - policy
            resources:
              - poddisruptionbudgets
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - backups
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - backups/status
            verbs:
              - get
              - patch
              - update
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - clusterimagecatalogs
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - clusters
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - clusters/finalizers
            verbs:
              - update
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - clusters/status
            verbs:
              - get
              - patch
              - update
              - watch
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - imagecatalogs
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - poolers
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - poolers/finalizers
            verbs:
              - update
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - poolers/status
            verbs:
              - get
              - patch
              - update
              - watch
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - scheduledbackups
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - postgresql.cnpg.io
            resources:
              - scheduledbackups/status
            verbs:
              - get
              - patch
              - update
          - apiGroups:
              - rbac.authorization.k8s.io
            resources:
              - rolebindings
            verbs:
              - create
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - rbac.authorization.k8s.io
            resources:
              - roles
            verbs:
              - create
              - get
              - list
              - patch
              - update
              - watch
          - apiGroups:
              - snapshot.storage.k8s.io
            resources:
              - volumesnapshots
            verbs:
              - create
              - get
              - list
              - patch
              - watch

required:
  - name
  - namespace