apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ubbagent-config
data:
  config.yaml: |
    # The identity section contains authentication information used
    # by the agent.
    identities:
      - name: gcp
        gcp:
          # This parameter accepts a base64-encoded JSON service
          # account key. The value comes from the reporting secret.
          encodedServiceAccountKey: $AGENT_ENCODED_KEY

    # The metrics section defines the metric that will be reported.
    # Metric names should match verbatim the identifiers created
    # during pricing setup.
    metrics:
      - name: {{ .Values.metering.reporting.metricName | quote }}
        type: double

        # The endpoints section of a metric defines which endpoints the
        # metric data is sent to.
        endpoints:
          - name: on_disk
          - name: servicecontrol

        passthrough: {}

    # The endpoints section defines where metering data is ultimately
    # sent. Currently supported endpoints include:
    # * disk - some directory on the local filesystem
    # * servicecontrol - Google Service Control
    endpoints:
      - name: on_disk
        # The disk endpoint is useful for debugging, but its inclusion
        # is not necessary in a production deployment.
        disk:
          reportDir: /var/lib/ubbagent/reports
          expireSeconds: 3600
      - name: servicecontrol
        servicecontrol:
          identity: gcp
          # The service name is unique to your application and will be
          # provided during onboarding.
          serviceName: {{ .Values.metering.reporting.serviceName | quote }}
          consumerId: $AGENT_CONSUMER_ID  # From the reporting secret.
